#!/bin/bash

echo -e "\e[1;42mAttention: no space around '='.\e[0m"
var="Hello, I'm Robin."

echo $var
echo ${var}


var2=5
echo -e "\e[1;42mBoth of them can be used in double quote\e[0m"
echo -e "\e[1;42mBut can not in sigle quote\e[0m"
echo "$var2"
echo "${var2}"
echo '${var2}'
echo '$var2'
